FROM NODE:18-alpine
WORKDIR /app
COPY . .
RUN npm i
RUN npm i brcypt
RUN npm i child_process
RUN npm i cors
RUN npm i dotenv
RUN npm i express
RUN npm i fs
RUN npm i jsonwebtoken
RUN npm i mongoose
RUN npm i nodemailer
RUN npm i nodemone
RUN npm i path
RUN npm i otp-generator
RUN npm i uuid
CMD ["node","index.js"]
